package uz.pdp.mockaroo.util.enums;

public enum FieldType {
    FIRSTNAME,  LASTNAME,   USERNAME,  FULLNAME, TITLE, PREFFIX, SUFFIX, BLOOD_GROUP,

    DIGIT, NUMBER_BETWEEN, RANDOM_NUMBER, RANDOM_DIGIT, RANDOM_DIGIT_NON_ZERO,

    CELL_PHONE, PHONE_NUMBER, SUBSCRIBER_NUMBER,

    COUNTRY, CITY, BUILDING_NUMBER, CITY_NAME, COUNTRY_CODE, FULL_ADDRESS, SECONDARY_ADDRESS, STREET_ADDRESS, STREET_ADDRESS_NUMBER, STREET_NAME,

    COLOR_NAME,

    DISH, FRUIT, INGREDIENT, MEASURMENT, SPICE, SUSHI, VEGETABLE,

    CAPITAL_CITY, FLAG, LANGUAGE, NATIONALITY,

    DESCRIPTION, TEMPERATURE_CELSIUS, TEMPERATURE_CELSIUS_PARAM, TEMPERATURE_FAHRENHEIT, TEMPERATURE_FAHRENHEIT_PARAM, CURRENCY_NAME, STRECURRENCY_CODE,

}
