spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://mockaroo.cdgdbfweslzx.us-east-1.rds.amazonaws.com:5432/postgres
    password: AB5939523
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  messages:
    always-use-message-format: true
springdoc:
  swagger-ui:
    path: /ui
  api-docs:
    path: /api-docs
    enabled: false

server:
  servlet:
    context-path: /api