spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    password: 1802
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


springdoc:
  swagger-ui:
    path: /ui
    enabled: true

server:
  servlet:
    context-path: /api