spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 5939523
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true
  messages:
    always-use-message-format: true
springdoc:
  swagger-ui:
    path: /ui
  api-docs:
    path: /api-docs
    enabled: false

server:
  servlet:
    context-path: /api