spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db
    username: sa
    password: sa

  h2:
    console:
      enabled: true
      path: /h2

springdoc:
  swagger-ui:
    path: /ui